
spring:
  datasource:
    driver-class-name : org.postgresql.Driver
    initialization-mode : always
    initialize : true
    url : jdbc:postgresql://localhost:5432/elora
    username : nicholas
    password : password
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
        order_inserts: true
    show-sql: true
